env:
  - DOCKER_COMPOSE_VERSION=1.25.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

before_script:
  - docker-compose run web bundle exec rake db:test:load

script:
  - docker-compose run --no-deps web bundle exec rspec --format documentation
  - docker-compose run --no-deps web bundle exec rake rswag

after_script:
  - docker-compose down
