---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/auth/login":
    post:
      summary: login authentication
      tags:
      - auth
      consumes:
      - application/json
      parameters:
      - name: auth
        in: query
        schema:
          type: object
          properties:
            email:
              type: string
            password:
              type: string
          required:
          - email
          - password
      responses:
        '200':
          description: ok
        '401':
          description: unauthorized
  "/comments":
    get:
      summary: list comments
      responses:
        '200':
          description: successful
    post:
      summary: create comment
      responses:
        '200':
          description: successful
  "/comments/{id}":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show comment
      responses:
        '200':
          description: successful
    patch:
      summary: update comment
      responses:
        '200':
          description: successful
    put:
      summary: update comment
      responses:
        '200':
          description: successful
    delete:
      summary: delete comment
      responses:
        '200':
          description: successful
  "/posts":
    get:
      summary: list posts
      responses:
        '200':
          description: successful
    post:
      summary: create post
      responses:
        '200':
          description: successful
  "/posts/{id}":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show post
      responses:
        '200':
          description: successful
    patch:
      summary: update post
      responses:
        '200':
          description: successful
    put:
      summary: update post
      responses:
        '200':
          description: successful
    delete:
      summary: delete post
      responses:
        '200':
          description: successful
  "/users":
    get:
      summary: list users
      tags:
      - User
      consumes:
      - application/json
      responses:
        '200':
          description: successful
    post:
      summary: create user
      tags:
      - User
      consumes:
      - application/json
      parameters:
      - name: body
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            username:
              type: string
            email:
              type: string
            password:
              type: string
            password_confirmation:
              type: string
          required:
          - name
          - username
          - email
          - password
          - password_confirmation
      responses:
        '201':
          description: successful
  "/users/{_username}":
    get:
      summary: show user
      tags:
      - User
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: _username
        in: path
        schema:
          type: string
          properties:
            _username:
              type: string
          required:
          - _username
        required: true
      responses:
        '200':
          description: successful
        '404':
          description: not found
